export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const SHOW_ERROR = "SHOW_ERROR";
export const SET_LAUNCH_FLAG = "SET_LAUNCH_FLAG";
export const SET_LAND_FLAG = "SET_LAND_FLAG";
export const SET_LAUNCH_YEAR = "SET_LAUNCH_YEAR";
export const MISSIONS_DATA_REQUEST = "MISSIONS_DATA_REQUEST";
export const SET_MISSIONS_DATA = "SET_MISSIONS_DATA";
export const FILTERED_MISSIONS_DATA_REQUEST = "FILTERED_MISSIONS_DATA_REQUEST";
